# -*- coding: utf-8 -*-
"""Tugas Certainly faktor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JbiKOiUQAGygLvMbmBQX88wovV7Vn5cy
"""

# Gejala yang dirasakan oleh user dan tingkat keyakinannya (CF user)
gejala_user = {
    "demam": 0.2,  # ✅ DIUBAH dari 0.7 → 0.2
    "batuk": 0.5,
    "sakit_tenggorokan": 0.6,
    "pilek": 0.7,
    "nyeri_otot": 0.5,
    "kelelahan": 0.4,
    "sakit_kepala": 0.3,
    "mual": 0.2
}

# Pengetahuan pakar: gejala dan bobot keyakinannya terhadap penyakit flu
pengetahuan = {
    "flu": {
        "demam": 0.8,
        "batuk": 0.7,
        "sakit_tenggorokan": 0.6,
        "pilek": 0.9,
        "nyeri_otot": 0.7,
        "kelelahan": 0.5,
        "sakit_kepala": 0.4,
        "mual": 0.2
    }
}

# Fungsi menghitung CF total
def hitung_cf(gejala_user, pengetahuan_pakar):
    cf_total = 0
    first = True
    for gejala, cf_user in gejala_user.items():
        if gejala in pengetahuan_pakar:
            cf_pakar = pengetahuan_pakar[gejala]
            cf = cf_user * cf_pakar
            if first:
                cf_total = cf
                first = False
            else:
                cf_total = cf_total + cf * (1 - cf_total)
    return cf_total

# Hitung CF diagnosis flu
cf_flu = hitung_cf(gejala_user, pengetahuan["flu"])
print(f"CF diagnosis Flu: {cf_flu:.2f}")

"""
1. Nilai CF gejala "demam" diubah dari 0.7 → 0.2. Ini menunjukkan bahwa keyakinan user terhadap gejala demam sangat rendah.Karena "demam" adalah gejala dengan bobot tinggi (0.8) dalam diagnosis flu, perubahan ini mengurangi kontribusi besar dalam perhitungan akhir.

2. penambahkan 5 gejala baru seperti pilek, nyeri otot, kelelahan, sakit kepala, dan mual, lengkap dengan CF user dan CF pakar.

3. Hasil CF diagnosis flu menjadi lebih proporsional, karena mempertimbangkan lebih banyak gejala yang relevan.

4. Meskipun "demam" memiliki pengaruh kecil sekarang, gejala lain seperti "pilek" (0.7 * 0.9) tetap memberikan kontribusi besar pada total CF.

Jadi, dengan semakin banyak gejala yang dipertimbangkan, sistem menjadi lebih fleksibel terhadap gejala utama yang lemah, dan tetap bisa memberikan diagnosis yang cukup akurat.
"""